from __future__ import annotations

import hashlib
import importlib.util
import json
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


generate_index = load("generate_index", ROOT / "scripts" / "generate_index.py")
check_compliance = load("check_compliance", ROOT / "scripts" / "check_compliance.py")


class CompliancePolicyTests(unittest.TestCase):
    version = "2026.03.17"
    commit = "a" * 40
    source_digest = "b" * 64

    def core_lock(self) -> dict:
        return {
            "schemaVersion": 2,
            "component": "fetchii-core",
            "version": self.version,
            "source": {
                "repository": "https://github.com/yt-dlp/yt-dlp.git",
                "tag": self.version,
                "commit": self.commit,
                "archiveUrl": (
                    "https://downloads.beamdrop.entromoonic.com/"
                    f"fetchii-core/sources/{self.version}/{self.commit}/"
                    f"{self.source_digest}.tar.gz"
                ),
                "archiveSha256": self.source_digest,
                "archiveSize": 123456,
            },
            "toolchain": {
                "pythonImplementation": "CPython",
                "pythonVersion": "3.12.10",
                "pipVersion": "25.1.1",
                "targetPlatform": "macos",
                "targetArchitecture": "universal2",
            },
            "dependencies": [
                {
                    "name": "mutagen",
                    "version": "1.47.0",
                    "artifacts": [
                        {
                            "scope": scope,
                            "url": (
                                "https://files.pythonhosted.org/packages/aa/"
                                f"{scope}/mutagen-1.47.0.tar.gz"
                            ),
                            "sha256": f"{index + 1:064x}",
                        }
                        for index, scope in enumerate(check_compliance.REQUIRED_SCOPES)
                    ],
                }
            ],
        }

    def write_lock(self, path: Path, value: dict, *, canonical: bool = True) -> bytes:
        if canonical:
            raw = check_compliance.canonical_json_bytes(value)
        else:
            raw = (json.dumps(value, indent=2) + "\n").encode("utf-8")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)
        return raw

    def render_record(self, lock: dict, lock_digest: str) -> str:
        source = lock["source"]
        toolchain = lock["toolchain"]
        rows = check_compliance.dependency_rows(lock)
        return "\n".join(
            [
                "<!-- generated by release_records.py; deterministic; do not edit -->",
                f"# fetchii-core {lock['version']} — corresponding-source record",
                "",
                "- **Schema:** `fetchii-core-record/v3`",
                "- **Display version:** `1234abcd`",
                (
                    "- **Artifact:** [immutable tarball]"
                    "(https://downloads.beamdrop.entromoonic.com/fetchii-core/"
                    f"{lock['version']}/fetchii-core.tar.gz) (`sha256: {'c' * 64}`)"
                ),
                f"- **Input lock:** [`{lock_digest}`](locks/{lock['version']}.json)",
                f"- **Source repository:** [{source['repository']}]({source['repository']})",
                f"- **yt-dlp tag:** `{source['tag']}`",
                (
                    f"- **yt-dlp commit:** [`{source['commit']}`]"
                    f"(https://github.com/yt-dlp/yt-dlp/commit/{source['commit']})"
                ),
                (
                    f"- **Locked source object:** [archive]({source['archiveUrl']}) "
                    f"(`sha256: {source['archiveSha256']}`, "
                    f"`{source['archiveSize']}` bytes)"
                ),
                (
                    "- **Toolchain:** "
                    f"{toolchain['pythonImplementation']} {toolchain['pythonVersion']}, "
                    f"pip {toolchain['pipVersion']}, "
                    f"{toolchain['targetPlatform']} {toolchain['targetArchitecture']}."
                ),
                (
                    "- **License:** the bundle includes `mutagen` under "
                    "GPLv2-or-later; see `../GPLv2.txt`."
                ),
                (
                    "- **Build recipe:** `python3 -m bundle.pyinstaller --onedir "
                    "--target-architecture universal2`."
                ),
                "",
                (
                    "Reproduction must use the locked source object and every "
                    "dependency artifact below."
                ),
                (
                    "Do not resolve a tag, `latest` URL, package range, or "
                    "installed environment again."
                ),
                "",
                "## Locked dependencies",
                "",
                "| Name | Exact version | Source artifact(s) |",
                "|---|---:|---|",
                *rows,
                "",
            ]
        )

    def validate_value(self, value: dict, *, canonical: bool = True) -> list[str]:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "lock.json"
            self.write_lock(path, value, canonical=canonical)
            return check_compliance.validate_lock(path, root=Path(temporary))

    def make_record_tree(self, root: Path) -> tuple[Path, Path, str]:
        lock = self.core_lock()
        lock_path = root / "fetchii-core" / "versions" / "locks" / f"{self.version}.json"
        raw = self.write_lock(lock_path, lock)
        digest = hashlib.sha256(raw).hexdigest()
        record_path = lock_path.parent.parent / f"{self.version}.md"
        record_path.write_text(self.render_record(lock, digest), encoding="utf-8")
        return record_path, lock_path, digest

    def test_index_is_byte_deterministic_and_current(self) -> None:
        first = generate_index.render()
        second = generate_index.render()
        self.assertEqual(first, second)
        self.assertEqual((ROOT / "fetchii-releases.md").read_bytes(), first)

    def test_repository_has_no_dead_local_markdown_links(self) -> None:
        self.assertEqual(check_compliance.local_link_errors(), [])

    def test_core_lock_v2_accepts_exact_source_toolchain_and_six_scopes(self) -> None:
        self.assertEqual(self.validate_value(self.core_lock()), [])

    def test_core_lock_requires_canonical_bytes_and_unique_json_keys(self) -> None:
        self.assertTrue(self.validate_value(self.core_lock(), canonical=False))
        value = self.core_lock()
        raw = check_compliance.canonical_json_bytes(value).decode("utf-8")
        duplicate = raw.replace(
            '"component":"fetchii-core",',
            '"component":"fetchii-core","component":"fetchii-core",',
        )
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "lock.json"
            path.write_text(duplicate, encoding="utf-8")
            errors = check_compliance.validate_lock(path, root=Path(temporary))
        self.assertTrue(any("duplicate" in error for error in errors))

    def test_core_lock_rejects_floating_or_noncanonical_pep440_version(self) -> None:
        for version in (">=1.47", "01.47.0"):
            with self.subTest(version):
                value = self.core_lock()
                value["dependencies"][0]["version"] = version
                errors = self.validate_value(value)
                self.assertTrue(any("version" in error for error in errors))

    def test_core_lock_requires_every_scope_and_runtime_mutagen(self) -> None:
        for mutation in ("missing-scope", "missing-runtime-mutagen"):
            with self.subTest(mutation):
                value = self.core_lock()
                artifacts = value["dependencies"][0]["artifacts"]
                scope = "repair" if mutation == "missing-scope" else "runtime"
                artifacts[:] = [item for item in artifacts if item["scope"] != scope]
                if mutation == "missing-runtime-mutagen":
                    value["dependencies"].append(
                        {
                            "name": "runtime-provider",
                            "version": "1.0",
                            "artifacts": [
                                {
                                    "scope": "runtime",
                                    "url": (
                                        "https://files.pythonhosted.org/packages/aa/"
                                        "runtime/provider-1.0.tar.gz"
                                    ),
                                    "sha256": "f" * 64,
                                }
                            ],
                        }
                    )
                self.assertTrue(self.validate_value(value))

    def test_core_lock_binds_source_tag_commit_url_digest_and_size(self) -> None:
        mutations = (
            ("tag", "2026.03.18"),
            ("commit", "not-a-commit"),
            ("archiveUrl", "https://example.com/latest.tar.gz"),
            ("archiveSha256", "not-a-digest"),
            ("archiveSize", 0),
            ("archiveSize", True),
        )
        for field, replacement in mutations:
            with self.subTest(field=field, replacement=replacement):
                value = self.core_lock()
                value["source"][field] = replacement
                self.assertTrue(self.validate_value(value))

    def test_core_lock_rejects_mutable_or_non_pypi_dependency_urls(self) -> None:
        for url in (
            "https://files.pythonhosted.org/packages/aa/runtime/file.whl?token=secret",
            "https://pypi.org/packages/aa/runtime/file.whl",
            "https://user@files.pythonhosted.org/packages/aa/runtime/file.whl",
            "https://files.pythonhosted.org/packages/aa/runtime/evil%0Afile.whl",
            "https://files.pythonhosted.org/packages/aa/runtime/evil%2Ffile.whl",
        ):
            with self.subTest(url):
                value = self.core_lock()
                value["dependencies"][0]["artifacts"][0]["url"] = url
                self.assertTrue(self.validate_value(value))

    def test_core_lock_requires_exact_cpython_macos_universal2_toolchain(self) -> None:
        for field, replacement in (
            ("pythonImplementation", "PyPy"),
            ("pythonVersion", "3.12"),
            ("pipVersion", ">=25"),
            ("pipVersion", "025.1.1"),
            ("targetPlatform", "linux"),
            ("targetArchitecture", "arm64"),
        ):
            with self.subTest(field):
                value = self.core_lock()
                value["toolchain"][field] = replacement
                self.assertTrue(self.validate_value(value))

    def test_core_record_independently_matches_lock_and_fixed_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            self.assertEqual(check_compliance.validate_core_record(record, root=root), [])

    def test_core_record_rejects_mutated_source_lock_or_dependency_claim(self) -> None:
        source_url = self.core_lock()["source"]["archiveUrl"]
        mutations = (
            (f"- **yt-dlp tag:** `{self.version}`", "- **yt-dlp tag:** `2026.03.18`"),
            (self.commit, "d" * 40),
            (source_url, "https://example.com/source.tar.gz"),
            (f"sha256: {self.source_digest}", "sha256: " + "e" * 64),
            ("`123456` bytes", "`123457` bytes"),
            ("sha256:" + f"{1:064x}", "sha256:" + "f" * 64),
        )
        for before, after in mutations:
            with self.subTest(before=before[:32]):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, _ = self.make_record_tree(root)
                    contents = record.read_text(encoding="utf-8")
                    self.assertIn(before, contents)
                    record.write_text(contents.replace(before, after, 1), encoding="utf-8")
                    self.assertTrue(check_compliance.validate_core_record(record, root=root))

    def test_core_record_rejects_lock_digest_and_filename_mismatch(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, digest = self.make_record_tree(root)
            contents = record.read_text(encoding="utf-8").replace(digest, "f" * 64, 1)
            record.write_text(contents, encoding="utf-8")
            self.assertTrue(check_compliance.validate_core_record(record, root=root))
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            wrong = record.with_name("2026.03.18.md")
            record.rename(wrong)
            self.assertTrue(check_compliance.validate_core_record(wrong, root=root))

    def test_generator_comment_alone_never_marks_record_locked(self) -> None:
        contents = (
            "<!-- generated by release_records.py; deterministic; do not edit -->\n"
            "# incomplete\n"
        )
        self.assertEqual(generate_index.status("fetchii-core", contents), "legacy/manual record")
        self.assertEqual(
            check_compliance.record_status("fetchii-core", contents),
            "legacy/manual record",
        )

    def test_v3_record_fields_are_classified_without_trusting_comment(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            contents = record.read_text(encoding="utf-8")
            self.assertEqual(generate_index.status("fetchii-core", contents), "locked v3 record")
            self.assertEqual(
                check_compliance.record_status("fetchii-core", contents),
                "locked v3 record",
            )


if __name__ == "__main__":
    unittest.main()
