from __future__ import annotations

import contextlib
import hashlib
import importlib.util
import io
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]


def load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


generate_index = load("generate_index", ROOT / "scripts" / "generate_index.py")
check_compliance = load("check_compliance", ROOT / "scripts" / "check_compliance.py")


class CompliancePolicyTests(unittest.TestCase):
    version = "2026.03.17"
    commit = "a" * 40
    source_digest = "b" * 64
    artifact_digest = "c" * 64
    display_version = "1234abcd"
    expected_dependency_row = (
        "| `mutagen` | `1.47.0` | "
        "`runtime` [sha256:"
        "0000000000000000000000000000000000000000000000000000000000000001]"
        "(https://files.pythonhosted.org/packages/aa/runtime/mutagen-1.47.0.tar.gz)<br>"
        "`build` [sha256:"
        "0000000000000000000000000000000000000000000000000000000000000002]"
        "(https://files.pythonhosted.org/packages/aa/build/mutagen-1.47.0.tar.gz)<br>"
        "`pyinstaller` [sha256:"
        "0000000000000000000000000000000000000000000000000000000000000003]"
        "(https://files.pythonhosted.org/packages/aa/pyinstaller/"
        "mutagen-1.47.0.tar.gz)<br>"
        "`repair` [sha256:"
        "0000000000000000000000000000000000000000000000000000000000000004]"
        "(https://files.pythonhosted.org/packages/aa/repair/mutagen-1.47.0.tar.gz)<br>"
        "`curl-arm64` [sha256:"
        "0000000000000000000000000000000000000000000000000000000000000005]"
        "(https://files.pythonhosted.org/packages/aa/curl-arm64/"
        "mutagen-1.47.0.tar.gz)<br>"
        "`curl-x86-64` "
        "[sha256:"
        "0000000000000000000000000000000000000000000000000000000000000006]"
        "(https://files.pythonhosted.org/packages/aa/curl-x86-64/"
        "mutagen-1.47.0.tar.gz) |"
    )

    @property
    def artifact_url(self) -> str:
        return (
            "https://downloads.beamdrop.entromoonic.com/fetchii-core/"
            f"fetchii-core_macos_{self.version}.tar.gz"
        )

    def core_lock(self) -> dict:
        return {
            "schemaVersion": 2,
            "component": "fetchii-core",
            "version": self.version,
            "source": {
                "repository": "https://github.com/yt-dlp/yt-dlp.git",
                "tag": self.version,
                "commit": self.commit,
                "archiveUrl": (
                    "https://downloads.beamdrop.entromoonic.com/"
                    f"fetchii-core/sources/{self.version}/{self.commit}/"
                    f"{self.source_digest}.tar.gz"
                ),
                "archiveSha256": self.source_digest,
                "archiveSize": 123456,
            },
            "toolchain": {
                "pythonImplementation": "CPython",
                "pythonVersion": "3.12.10",
                "pipVersion": "25.1.1",
                "targetPlatform": "macos",
                "targetArchitecture": "universal2",
            },
            "dependencies": [
                {
                    "name": "mutagen",
                    "version": "1.47.0",
                    "artifacts": [
                        {
                            "scope": scope,
                            "url": (
                                "https://files.pythonhosted.org/packages/aa/"
                                f"{scope}/mutagen-1.47.0.tar.gz"
                            ),
                            "sha256": f"{index + 1:064x}",
                        }
                        for index, scope in enumerate(
                            (
                                "runtime",
                                "build",
                                "pyinstaller",
                                "repair",
                                "curl-arm64",
                                "curl-x86-64",
                            )
                        )
                    ],
                }
            ],
        }

    def write_lock(self, path: Path, value: dict, *, canonical: bool = True) -> bytes:
        if canonical:
            raw = check_compliance.canonical_json_bytes(value)
        else:
            raw = (json.dumps(value, indent=2) + "\n").encode("utf-8")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)
        return raw

    def render_record(self, lock: dict, lock_digest: str) -> str:
        source = lock["source"]
        toolchain = lock["toolchain"]
        return "\n".join(
            [
                "<!-- generated by release_records.py; deterministic; do not edit -->",
                f"# fetchii-core {lock['version']} — corresponding-source record",
                "",
                "- **Schema:** `fetchii-core-record/v3`",
                f"- **Display version:** `{self.display_version}`",
                (
                    "- **Artifact:** [immutable tarball]"
                    f"({self.artifact_url}) (`sha256: {self.artifact_digest}`)"
                ),
                f"- **Input lock:** [`{lock_digest}`](locks/{lock['version']}.json)",
                f"- **Source repository:** [{source['repository']}]({source['repository']})",
                f"- **yt-dlp tag:** `{source['tag']}`",
                (
                    f"- **yt-dlp commit:** [`{source['commit']}`]"
                    f"(https://github.com/yt-dlp/yt-dlp/commit/{source['commit']})"
                ),
                (
                    f"- **Locked source object:** [archive]({source['archiveUrl']}) "
                    f"(`sha256: {source['archiveSha256']}`, "
                    f"`{source['archiveSize']}` bytes)"
                ),
                (
                    "- **Toolchain:** "
                    f"{toolchain['pythonImplementation']} {toolchain['pythonVersion']}, "
                    f"pip {toolchain['pipVersion']}, "
                    f"{toolchain['targetPlatform']} {toolchain['targetArchitecture']}."
                ),
                (
                    "- **License:** the bundle includes `mutagen` under "
                    "GPLv2-or-later; see `../GPLv2.txt`."
                ),
                (
                    "- **Build recipe:** `python3 -m bundle.pyinstaller --onedir "
                    "--target-architecture universal2`."
                ),
                "",
                (
                    "Reproduction must use the locked source object and every "
                    "dependency artifact below."
                ),
                (
                    "Do not resolve a tag, `latest` URL, package range, or "
                    "installed environment again."
                ),
                "",
                "## Locked dependencies",
                "",
                "| Name | Exact version | Source artifact(s) |",
                "|---|---:|---|",
                self.expected_dependency_row,
                "",
            ]
        )

    def release_manifest(self, lock_digest: str) -> dict:
        return {
            "schemaVersion": 1,
            "component": "fetchii-core",
            "version": self.version,
            "displayVersion": self.display_version,
            "artifactUrl": self.artifact_url,
            "artifactSha256": self.artifact_digest,
            "inputLockSha256": lock_digest,
        }

    def write_manifest(
        self, path: Path, value: dict, *, canonical: bool = True
    ) -> bytes:
        if canonical:
            raw = check_compliance.canonical_json_bytes(value)
        else:
            raw = (json.dumps(value, indent=2) + "\n").encode("utf-8")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)
        return raw

    def validate_value(self, value: dict, *, canonical: bool = True) -> list[str]:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "lock.json"
            self.write_lock(path, value, canonical=canonical)
            return check_compliance.validate_lock(path, root=Path(temporary))

    def make_record_tree(self, root: Path) -> tuple[Path, Path, str]:
        for component in ("aria2", "fetchii-core", "ffmpeg"):
            (root / component / "versions").mkdir(parents=True, exist_ok=True)
        lock = self.core_lock()
        lock_path = root / "fetchii-core" / "versions" / "locks" / f"{self.version}.json"
        raw = self.write_lock(lock_path, lock)
        digest = hashlib.sha256(raw).hexdigest()
        record_path = lock_path.parent.parent / f"{self.version}.md"
        record_path.write_text(self.render_record(lock, digest), encoding="utf-8")
        manifest_path = (
            record_path.parent / "manifests" / f"{self.version}.json"
        )
        self.write_manifest(manifest_path, self.release_manifest(digest))
        return record_path, lock_path, digest

    def validate_record(self, record: Path, *, root: Path) -> list[str]:
        return check_compliance.validate_core_record(
            record,
            artifact_url=self.artifact_url,
            artifact_sha256=self.artifact_digest,
            display_version=self.display_version,
            root=root,
        )

    def test_index_is_byte_deterministic_and_current(self) -> None:
        first = generate_index.render()
        second = generate_index.render()
        self.assertEqual(first, second)
        self.assertEqual((ROOT / "fetchii-releases.md").read_bytes(), first)

    def test_index_cli_check_write_and_error_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            for component in generate_index.COMPONENTS:
                (root / component / "versions").mkdir(parents=True)
            output = root / "fetchii-releases.md"
            expected = generate_index.render(root=root)
            stdout = io.StringIO()
            stderr = io.StringIO()
            with (
                mock.patch.object(generate_index, "ROOT", root),
                mock.patch.object(generate_index, "OUTPUT", output),
                contextlib.redirect_stdout(stdout),
                contextlib.redirect_stderr(stderr),
            ):
                with mock.patch.object(
                    generate_index.sys, "argv", ["generate_index.py", "--check"]
                ):
                    self.assertEqual(generate_index.main(), 1)
                    output.write_bytes(b"stale\n")
                    self.assertEqual(generate_index.main(), 1)
                    output.write_bytes(expected)
                    self.assertEqual(generate_index.main(), 0)
                with mock.patch.object(
                    generate_index.sys, "argv", ["generate_index.py"]
                ):
                    output.write_bytes(b"stale again\n")
                    self.assertEqual(generate_index.main(), 0)
                    self.assertEqual(output.read_bytes(), expected)

    def test_index_title_and_aria_status_error_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "record.md"
            path.write_text("no markdown title\n", encoding="utf-8")
            with self.assertRaises(ValueError):
                generate_index.title(path)
        aria = (
            "- **Schema:** `aria2-record/v2`\n"
            f"- **Artifact:** `sha256: {'a' * 64}`\n"
            f"- **Source:** `sha256: {'b' * 64}`\n"
            "- **Source revision:** `release-1.37.0`\n"
        )
        self.assertEqual(generate_index.status("aria2", aria), "locked v2 record")

    def test_repository_has_no_dead_local_markdown_links(self) -> None:
        self.assertEqual(check_compliance.local_link_errors(), [])

    def test_repository_policy_main_passes(self) -> None:
        self.assertEqual(check_compliance.main(), 0)

    def test_workflow_policy_requires_tests_read_only_permissions_and_pins(self) -> None:
        self.assertEqual(check_compliance.workflow_policy_errors(), [])
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            path = root / check_compliance.POLICY_WORKFLOW
            path.parent.mkdir(parents=True)
            path.write_text(
                "permissions:\n  contents: write\n\njobs:\n"
                "  test:\n    steps:\n      - uses: actions/checkout@v4\n",
                encoding="utf-8",
            )
            errors = check_compliance.workflow_policy_errors(root=root)
            self.assertTrue(any("read-only" in error for error in errors))
            self.assertTrue(any("unittest" in error for error in errors))
            self.assertTrue(any("full commit" in error for error in errors))
        with tempfile.TemporaryDirectory() as temporary:
            errors = check_compliance.workflow_policy_errors(root=Path(temporary))
            self.assertTrue(any("cannot safely open" in error for error in errors))
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            path = root / check_compliance.POLICY_WORKFLOW
            path.parent.mkdir(parents=True)
            path.write_bytes(b"\xff")
            errors = check_compliance.workflow_policy_errors(root=root)
            self.assertTrue(any("invalid UTF-8" in error for error in errors))

    def test_core_lock_v2_accepts_exact_source_toolchain_and_six_scopes(self) -> None:
        self.assertEqual(self.validate_value(self.core_lock()), [])

    def test_core_lock_requires_canonical_bytes_and_unique_json_keys(self) -> None:
        self.assertTrue(self.validate_value(self.core_lock(), canonical=False))
        value = self.core_lock()
        raw = check_compliance.canonical_json_bytes(value).decode("utf-8")
        duplicate = raw.replace(
            '"component":"fetchii-core",',
            '"component":"fetchii-core","component":"fetchii-core",',
        )
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "lock.json"
            path.write_text(duplicate, encoding="utf-8")
            errors = check_compliance.validate_lock(path, root=Path(temporary))
        self.assertTrue(any("duplicate" in error for error in errors))

    def test_core_lock_rejects_floating_or_noncanonical_pep440_version(self) -> None:
        for version in (">=1.47", "01.47.0"):
            with self.subTest(version):
                value = self.core_lock()
                value["dependencies"][0]["version"] = version
                errors = self.validate_value(value)
                self.assertTrue(any("version" in error for error in errors))

    def test_core_lock_requires_every_scope_and_runtime_mutagen(self) -> None:
        for mutation in ("missing-scope", "missing-runtime-mutagen"):
            with self.subTest(mutation):
                value = self.core_lock()
                artifacts = value["dependencies"][0]["artifacts"]
                scope = "repair" if mutation == "missing-scope" else "runtime"
                artifacts[:] = [item for item in artifacts if item["scope"] != scope]
                if mutation == "missing-runtime-mutagen":
                    value["dependencies"].append(
                        {
                            "name": "runtime-provider",
                            "version": "1.0",
                            "artifacts": [
                                {
                                    "scope": "runtime",
                                    "url": (
                                        "https://files.pythonhosted.org/packages/aa/"
                                        "runtime/provider-1.0.tar.gz"
                                    ),
                                    "sha256": "f" * 64,
                                }
                            ],
                        }
                    )
                self.assertTrue(self.validate_value(value))

    def test_core_lock_binds_source_tag_commit_url_digest_and_size(self) -> None:
        mutations = (
            ("tag", "2026.03.18"),
            ("commit", "not-a-commit"),
            ("archiveUrl", "https://example.com/latest.tar.gz"),
            ("archiveSha256", "not-a-digest"),
            ("archiveSize", 0),
            ("archiveSize", True),
        )
        for field, replacement in mutations:
            with self.subTest(field=field, replacement=replacement):
                value = self.core_lock()
                value["source"][field] = replacement
                self.assertTrue(self.validate_value(value))

    def test_core_lock_rejects_mutable_or_non_pypi_dependency_urls(self) -> None:
        for url in (
            "https://files.pythonhosted.org/packages/aa/runtime/file.whl?token=secret",
            "https://pypi.org/packages/aa/runtime/file.whl",
            "https://user@files.pythonhosted.org/packages/aa/runtime/file.whl",
            "https://files.pythonhosted.org/packages/aa/runtime/evil%0Afile.whl",
            "https://files.pythonhosted.org/packages/aa/runtime/evil%2Ffile.whl",
        ):
            with self.subTest(url):
                value = self.core_lock()
                value["dependencies"][0]["artifacts"][0]["url"] = url
                self.assertTrue(self.validate_value(value))

    def test_core_lock_requires_exact_cpython_macos_universal2_toolchain(self) -> None:
        for field, replacement in (
            ("pythonImplementation", "PyPy"),
            ("pythonVersion", "3.12"),
            ("pipVersion", ">=25"),
            ("pipVersion", "025.1.1"),
            ("targetPlatform", "linux"),
            ("targetArchitecture", "arm64"),
        ):
            with self.subTest(field):
                value = self.core_lock()
                value["toolchain"][field] = replacement
                self.assertTrue(self.validate_value(value))

    def test_core_record_independently_matches_lock_and_fixed_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            self.assertEqual(self.validate_record(record, root=root), [])
            self.assertEqual(
                check_compliance.validate_manifest_bound_core_record(
                    record, root=root
                ),
                [],
            )
            self.assertEqual(check_compliance.generated_record_errors(root=root), [])

    def test_core_record_full_byte_oracle_rejects_every_unlocked_field(self) -> None:
        mutations = (
            ("- **Display version:** `1234abcd`", "- **Display version:** `deadbeef`"),
            (
                "- **License:** the bundle includes `mutagen` under GPLv2-or-later; "
                "see `../GPLv2.txt`.",
                "- **License:** unknown",
            ),
            (
                "- **Build recipe:** `python3 -m bundle.pyinstaller --onedir "
                "--target-architecture universal2`.",
                "- **Build recipe:** `pip install latest`.",
            ),
            (
                "Reproduction must use the locked source object and every "
                "dependency artifact below.",
                "Reproduction may redownload dependencies.",
            ),
            (
                "Do not resolve a tag, `latest` URL, package range, or "
                "installed environment again.",
                "Resolve the current environment again.",
            ),
        )
        for before, after in mutations:
            with self.subTest(before=before[:32]):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, _ = self.make_record_tree(root)
                    contents = record.read_text(encoding="utf-8")
                    self.assertIn(before, contents)
                    record.write_text(
                        contents.replace(before, after, 1), encoding="utf-8"
                    )
                    self.assertTrue(self.validate_record(record, root=root))

    def test_core_record_rejects_duplicate_or_conflicting_fields(self) -> None:
        additions = (
            "- **Display version:** `deadbeef`\n",
            f"- **Artifact:** [immutable tarball]({self.artifact_url}) "
            f"(`sha256: {'d' * 64}`)\n",
            "- **License:** conflicting license claim\n",
            "Reproduction may use `latest`.\n",
        )
        for addition in additions:
            with self.subTest(addition=addition[:40]):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, _ = self.make_record_tree(root)
                    record.write_bytes(record.read_bytes() + addition.encode("utf-8"))
                    self.assertTrue(
                        check_compliance.validate_manifest_bound_core_record(
                            record, root=root
                        )
                    )

    def test_core_record_oracle_rejects_byte_boundary_changes(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            canonical = record.read_bytes()
            mutations = (
                canonical[:-1],
                canonical + b"\n",
                b"\xef\xbb\xbf" + canonical,
                canonical.replace(b"\n", b"\r\n"),
            )
            for mutation in mutations:
                with self.subTest(prefix=mutation[:12], size=len(mutation)):
                    record.write_bytes(mutation)
                    self.assertTrue(
                        check_compliance.validate_manifest_bound_core_record(
                            record, root=root
                        )
                    )
                    record.write_bytes(canonical)

    def test_core_record_rejects_latest_or_foreign_artifact_url(self) -> None:
        for replacement in (
            "https://downloads.beamdrop.entromoonic.com/fetchii-core/latest.tar.gz",
            f"https://example.com/fetchii-core_macos_{self.version}.tar.gz",
        ):
            with self.subTest(replacement=replacement):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, _ = self.make_record_tree(root)
                    contents = record.read_text(encoding="utf-8")
                    record.write_text(
                        contents.replace(self.artifact_url, replacement, 1),
                        encoding="utf-8",
                    )
                    errors = check_compliance.validate_manifest_bound_core_record(
                        record, root=root
                    )
                    self.assertTrue(
                        any("canonical lock-bound oracle" in error for error in errors)
                    )

    def test_generated_policy_rejects_display_or_artifact_digest_record_tamper(
        self,
    ) -> None:
        for before, after in (
            (self.display_version, "deadbeef"),
            (self.artifact_digest, "d" * 64),
        ):
            with self.subTest(before=before[:12]):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, _ = self.make_record_tree(root)
                    contents = record.read_text(encoding="utf-8")
                    record.write_text(
                        contents.replace(before, after, 1), encoding="utf-8"
                    )
                    errors = check_compliance.generated_record_errors(root=root)
                    self.assertTrue(
                        any("canonical lock-bound oracle" in error for error in errors)
                    )

    def test_release_manifest_is_canonical_strict_and_lock_bound(self) -> None:
        mutations = (
            ("displayVersion", "not-hex"),
            ("artifactSha256", "d" * 63),
            ("artifactUrl", "https://example.com/latest.tar.gz"),
            ("inputLockSha256", "e" * 64),
            ("version", "2026.03.18"),
            ("component", "other"),
            ("schemaVersion", 2),
        )
        for field, replacement in mutations:
            with self.subTest(field=field):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, digest = self.make_record_tree(root)
                    manifest_path = (
                        record.parent / "manifests" / f"{self.version}.json"
                    )
                    manifest = self.release_manifest(digest)
                    manifest[field] = replacement
                    self.write_manifest(manifest_path, manifest)
                    self.assertTrue(
                        check_compliance.generated_record_errors(root=root)
                    )

        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, digest = self.make_record_tree(root)
            manifest_path = record.parent / "manifests" / f"{self.version}.json"
            self.write_manifest(
                manifest_path, self.release_manifest(digest), canonical=False
            )
            errors = check_compliance.generated_record_errors(root=root)
            self.assertTrue(any("not canonical" in error for error in errors))

        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, digest = self.make_record_tree(root)
            manifest_path = record.parent / "manifests" / f"{self.version}.json"
            manifest = self.release_manifest(digest)
            manifest["unexpected"] = True
            self.write_manifest(manifest_path, manifest)
            errors = check_compliance.generated_record_errors(root=root)
            self.assertTrue(any("unexpected" in error for error in errors))

        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            manifest_path = record.parent / "manifests" / f"{self.version}.json"
            raw = manifest_path.read_text(encoding="utf-8")
            raw = raw.replace(
                '"component":"fetchii-core",',
                '"component":"fetchii-core","component":"fetchii-core",',
                1,
            )
            manifest_path.write_text(raw, encoding="utf-8")
            errors = check_compliance.generated_record_errors(root=root)
            self.assertTrue(any("duplicate" in error for error in errors))

    def test_generated_policy_rejects_boolean_or_float_manifest_schema(self) -> None:
        for schema_version in (True, 1.0):
            with self.subTest(schema_version=schema_version):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, digest = self.make_record_tree(root)
                    manifest_path = (
                        record.parent / "manifests" / f"{self.version}.json"
                    )
                    manifest = self.release_manifest(digest)
                    manifest["schemaVersion"] = schema_version
                    self.write_manifest(manifest_path, manifest)
                    errors = check_compliance.generated_record_errors(root=root)
                    self.assertTrue(
                        any("unsupported" in error for error in errors)
                    )

    def test_generated_policy_requires_independent_release_manifest(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            manifest_path = record.parent / "manifests" / f"{self.version}.json"
            manifest_path.unlink()
            errors = check_compliance.generated_record_errors(root=root)
            self.assertTrue(
                any("release manifest is invalid" in error for error in errors)
            )

    def test_core_record_oracle_rejects_missing_dependency_scope(self) -> None:
        scopes = (
            "runtime",
            "build",
            "pyinstaller",
            "repair",
            "curl-arm64",
            "curl-x86-64",
        )
        for scope in scopes:
            with self.subTest(scope=scope):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, _ = self.make_record_tree(root)
                    contents = record.read_text(encoding="utf-8")
                    start = contents.index(f"`{scope}` [sha256:")
                    separator = contents.find("<br>", start)
                    if separator >= 0:
                        end = separator + len("<br>")
                    else:
                        end = contents.index(" |", start)
                    record.write_text(
                        contents[:start] + contents[end:], encoding="utf-8"
                    )
                    errors = check_compliance.validate_manifest_bound_core_record(
                        record, root=root
                    )
                    self.assertTrue(
                        any(
                            "canonical lock-bound oracle" in error
                            for error in errors
                        )
                    )

    def test_record_renderer_rejects_invalid_independent_inputs(self) -> None:
        lock = self.core_lock()
        raw_lock = check_compliance.canonical_json_bytes(lock)
        mutations = (
            {"display_version": "not-hex"},
            {"artifact_sha256": "d" * 63},
            {"artifact_url": "https://example.com/latest.tar.gz"},
        )
        defaults = {
            "display_version": self.display_version,
            "artifact_sha256": self.artifact_digest,
            "artifact_url": self.artifact_url,
        }
        for mutation in mutations:
            with self.subTest(mutation=mutation):
                arguments = defaults | mutation
                with self.assertRaises(check_compliance.ComplianceError):
                    check_compliance.render_core_record(
                        lock, raw_lock, **arguments
                    )

        lock["version"] = 1
        with self.assertRaises(check_compliance.ComplianceError):
            check_compliance.render_core_record(
                lock,
                raw_lock,
                artifact_url=self.artifact_url,
                artifact_sha256=self.artifact_digest,
                display_version=self.display_version,
            )

    def test_policy_rejects_orphan_and_unexpected_sidecar_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            record.unlink()
            errors = check_compliance.generated_record_errors(root=root)
            self.assertTrue(
                any("input lock has no fixed-path record" in error for error in errors)
            )
            self.assertTrue(
                any("release manifest has no fixed-path record" in e for e in errors)
            )

        unexpected_paths = (
            ("versions", "unexpected.txt"),
            ("locks", "unexpected.txt"),
            ("manifests", "unexpected.txt"),
        )
        for directory, name in unexpected_paths:
            with self.subTest(directory=directory):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, _ = self.make_record_tree(root)
                    base = (
                        record.parent
                        if directory == "versions"
                        else record.parent / directory
                    )
                    (base / name).write_text("unexpected\n", encoding="utf-8")
                    self.assertTrue(check_compliance.generated_record_errors(root=root))

    def test_policy_rejects_nested_linked_or_hardlinked_sidecars(self) -> None:
        for directory in ("locks", "manifests"):
            for kind in ("nested", "symlink", "hardlink"):
                with self.subTest(directory=directory, kind=kind):
                    with tempfile.TemporaryDirectory() as temporary:
                        root = Path(temporary)
                        record, lock, _ = self.make_record_tree(root)
                        container = record.parent / directory
                        target = (
                            lock
                            if directory == "locks"
                            else container / f"{self.version}.json"
                        )
                        unexpected = container / "unexpected.json"
                        if kind == "nested":
                            unexpected.mkdir()
                            (unexpected / "nested.json").write_text(
                                "{}\n", encoding="utf-8"
                            )
                        elif kind == "symlink":
                            unexpected.symlink_to(target.name)
                        else:
                            os.link(target, unexpected)
                        errors = check_compliance.generated_record_errors(root=root)
                        self.assertTrue(
                            any("unexpected path" in error for error in errors)
                        )

    def test_core_record_rejects_mutated_source_lock_or_dependency_claim(self) -> None:
        source_url = self.core_lock()["source"]["archiveUrl"]
        mutations = (
            (f"- **yt-dlp tag:** `{self.version}`", "- **yt-dlp tag:** `2026.03.18`"),
            (self.commit, "d" * 40),
            (source_url, "https://example.com/source.tar.gz"),
            (f"sha256: {self.source_digest}", "sha256: " + "e" * 64),
            ("`123456` bytes", "`123457` bytes"),
            ("sha256:" + f"{1:064x}", "sha256:" + "f" * 64),
        )
        for before, after in mutations:
            with self.subTest(before=before[:32]):
                with tempfile.TemporaryDirectory() as temporary:
                    root = Path(temporary)
                    record, _, _ = self.make_record_tree(root)
                    contents = record.read_text(encoding="utf-8")
                    self.assertIn(before, contents)
                    record.write_text(
                        contents.replace(before, after, 1), encoding="utf-8"
                    )
                    self.assertTrue(self.validate_record(record, root=root))

    def test_core_record_rejects_lock_digest_and_filename_mismatch(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, digest = self.make_record_tree(root)
            contents = record.read_text(encoding="utf-8").replace(digest, "f" * 64, 1)
            record.write_text(contents, encoding="utf-8")
            self.assertTrue(self.validate_record(record, root=root))
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            wrong = record.with_name("2026.03.18.md")
            record.rename(wrong)
            self.assertTrue(self.validate_record(wrong, root=root))

    def test_core_record_rejects_noncanonical_lock_link(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            canonical = f"locks/{self.version}.json"
            contents = record.read_text(encoding="utf-8")
            self.assertIn(canonical, contents)
            record.write_text(
                contents.replace(canonical, f"locks/other-{self.version}.json", 1),
                encoding="utf-8",
            )
            self.assertTrue(self.validate_record(record, root=root))

    def test_nested_version_record_is_rejected_and_never_indexed(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            for component in generate_index.COMPONENTS:
                (root / component / "versions").mkdir(parents=True)
            nested = root / "fetchii-core" / "versions" / "rogue" / "2026.03.17.md"
            nested.parent.mkdir()
            nested.write_text(
                "# fetchii-core 2026.03.17 — corresponding-source record\n"
                "- **Schema:** `fetchii-core-record/v3`\n",
                encoding="utf-8",
            )
            errors = check_compliance.generated_record_errors(root=root)
            self.assertTrue(
                any("nested version paths are forbidden" in error for error in errors)
            )
            self.assertEqual(generate_index.records("fetchii-core", root=root), [])
            rendered = generate_index.render(root=root).decode("utf-8")
            self.assertNotIn("2026.03.17 — corresponding-source record", rendered)
            self.assertNotIn("rogue/2026.03.17.md", rendered)

    def test_generator_comment_alone_never_marks_record_locked(self) -> None:
        contents = (
            "<!-- generated by release_records.py; deterministic; do not edit -->\n"
            "# incomplete\n"
        )
        self.assertEqual(generate_index.status("fetchii-core", contents), "legacy/manual record")
        self.assertEqual(
            check_compliance.record_status("fetchii-core", contents),
            "legacy/manual record",
        )

    def test_v3_record_fields_are_classified_without_trusting_comment(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            record, _, _ = self.make_record_tree(root)
            contents = record.read_text(encoding="utf-8")
            self.assertEqual(generate_index.status("fetchii-core", contents), "locked v3 record")
            self.assertEqual(
                check_compliance.record_status("fetchii-core", contents),
                "locked v3 record",
            )


if __name__ == "__main__":
    unittest.main()
