#!/usr/bin/env python3
"""Generate the aggregate component-record index deterministically."""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "fetchii-releases.md"
COMPONENTS = ("aria2", "fetchii-core", "ffmpeg")
SHA_IN_RECORD = re.compile(r"sha256: ([0-9a-f]{64})")


def title(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    raise ValueError(f"record has no title: {path.relative_to(ROOT)}")


def status(component: str, contents: str) -> str:
    """Classify from required schema fields, never from a generator comment alone."""
    if "<SHA256" in contents or "auto-filled" in contents:
        return "legacy recipe; digest not recorded"
    digests = SHA_IN_RECORD.findall(contents)
    if component == "fetchii-core" and (
        "`fetchii-core-record/v3`" in contents
        and len(digests) >= 2
        and re.search(
            r"Input lock:\*\* \[`[0-9a-f]{64}`\]"
            r"\(locks/[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.json\)",
            contents,
        )
        and re.search(r"yt-dlp tag:\*\* `[0-9]{4}\.[0-9]{2}\.[0-9]{2}`", contents)
        and re.search(r"yt-dlp commit:\*\* \[`[0-9a-f]{40}`\]", contents)
        and "## Locked dependencies" in contents
    ):
        return "locked v3 record"
    if component == "aria2" and (
        "`aria2-record/v2`" in contents
        and len(digests) >= 2
        and re.search(
            r"Source revision:\*\* `release-[0-9]+\.[0-9]+\.[0-9]+`",
            contents,
        )
    ):
        return "locked v2 record"
    return "legacy/manual record"


def records(component: str, *, root: Path = ROOT) -> list[tuple[Path, str, str]]:
    directory = root / component / "versions"
    result = []
    for path in sorted(directory.glob("*.md")):
        if path.name == "TEMPLATE.md":
            continue
        contents = path.read_text(encoding="utf-8")
        result.append((path, title(path), status(component, contents)))
    return result


def render(*, root: Path = ROOT) -> bytes:
    lines = [
        "<!-- generated by scripts/generate_index.py; do not edit -->",
        "# Fetchii redistributed-component record index",
        "",
        "This is a deterministic convenience index of per-component records.",
        "The component record and its canonical lock remain the primary evidence path;",
        "this page does not make a legal sufficiency claim or map app release numbers.",
        "",
    ]
    for component in COMPONENTS:
        lines.extend(
            [
                f"## {component}",
                "",
                "| Record | Status |",
                "|---|---|",
            ]
        )
        component_records = records(component, root=root)
        if not component_records:
            lines.append("| _No release record yet_ | — |")
        else:
            for path, record_title, record_status in component_records:
                relative = path.relative_to(root).as_posix()
                lines.append(f"| [{record_title}]({relative}) | {record_status} |")
        lines.append("")
    return "\n".join(lines).encode("utf-8")


def atomic_write(path: Path, payload: bytes) -> None:
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        try:
            actual = OUTPUT.read_bytes()
        except OSError:
            actual = b""
        if actual != expected:
            print(
                "error: fetchii-releases.md is stale; run scripts/generate_index.py",
                file=sys.stderr,
            )
            return 1
        print("Aggregate record index is current.")
        return 0
    atomic_write(OUTPUT, expected)
    print(OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
